### ISSUE TITLE
Question L2D.left and .right

### ISSUE THREAD

**Issue by loete** [rladstaetter/fhj.swengb.assignments.tree#1]
A question to L2D.left and L2D.right.

```scala
val root = L2D.apply(start,initialAngle,length,cM(0)
val left = root.left(factor,angle,cM(0))
val right = root.right(factor,angle,cM(0))
```
Within this example I calculate the first L2D (`root`), when i apply `.left` and `.right` to `root` next L2D lines (`left`,`right`) will be returned.

But when I run this against your test everything is ok except the x coordianate of the second point, there is always the initial length of 100 missing.

```
Expected: Branch(Node(L2D(Pt2D(0.0,0.0),Pt2D(100.0,0.0),0xbc8f8fff)),Branch(Node(L2D(Pt2D(100.0,0.0),Pt2D(199.985,-1.745),0xbc8f8fff)),Node(L2D(Pt2D(100.0,0.0),Pt2D(199.985,1.745),0xbc8f8fff))))
Actual:   Branch(Node(L2D(Pt2D(0.0,0.0),Pt2D(100.0,0.0),0xbc8f8fff)),Branch(Node(L2D(Pt2D(100.0,0.0),Pt2D(99.985,-1.745),0xbc8f8fff)),Node(L2D(Pt2D(100.0,0.0),Pt2D(99.985,1.745),0xbc8f8fff))))
````
Sry, but have no idea what I am doing wrong with `L2D.left` and `L2D.right` or why there are always exactly 100 are missing to the expected value.

**Comment by rladstaetter** [comment]
- you have to implement L2D.apply(..) correctly.
- left and right are already implemented.

recipe for implementing L2D.apply(...)

- endpoint = startpoint + vector
- call case class constructor with startpoint and endpoint

you'll need toRadiants(...) function, and you have to calculate the x and y coordinate of the endpoint individually.

hope this helps.

**Comment by loete** [comment]
Thanks,

my `.apply` function calculated the endpoint wrong, forgot to include the startpoint in the calculation :unamused:
